"""SASTbench HTML report generator.

Generates a shareable HTML report from benchmark results JSON.
Supports both benchmark and PR mode results.

Usage:
    python scripts/report.py results.json
    python scripts/report.py results.json --verbose
    python scripts/report.py results.json -o report.html --verbose
"""

import argparse
import html
import json
import os
import sys
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SASTbench Report - {scanner_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.5rem; }}
  .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
  .metric {{ background: #f5f5f5; border-radius: 8px; padding: 1rem; text-align: center; }}
  .metric .value {{ font-size: 2rem; font-weight: bold; }}
  .metric .label {{ font-size: 0.85rem; color: #666; margin-top: 0.25rem; }}
  .agentic {{ background: #e8f5e9; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1.5rem 0; }}
  th, td {{ padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #ddd; vertical-align: top; }}
  th {{ background: #f5f5f5; font-weight: 600; }}
  .tp {{ color: #2e7d32; }}
  .fn {{ color: #c62828; }}
  .cap-fp {{ color: #e65100; }}
  .fp {{ color: #f57f17; }}
  .mono {{ font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 0.85rem; word-break: break-word; }}
  .small {{ color: #666; font-size: 0.85rem; }}
  details {{ margin: 0.5rem 0 1rem 0; }}
  summary {{ cursor: pointer; font-weight: 600; padding: 0.3rem 0; }}
  .finding {{ border-left: 3px solid #ddd; padding: 0.5rem 0.75rem; margin: 0.4rem 0; font-size: 0.85rem; }}
  .finding.tp {{ border-color: #2e7d32; background: #f1f8e9; }}
  .finding.fp {{ border-color: #f57f17; background: #fffde7; }}
  .finding.cap-fp {{ border-color: #c62828; background: #fce4ec; }}
  .finding .tag {{ display: inline-block; padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 0.75rem; font-weight: 600; color: #fff; margin-right: 0.5rem; }}
  .finding .tag.tp {{ background: #2e7d32; }}
  .finding .tag.fp {{ background: #f57f17; }}
  .finding .tag.cap-fp {{ background: #c62828; }}
  .finding .meta {{ color: #555; font-size: 0.8rem; }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #999; font-size: 0.8rem; }}
</style>
</head>
<body>
<h1>SASTbench Report</h1>
<div class="meta">
  <strong>Scanner:</strong> {scanner_name} v{scanner_version} &nbsp;|&nbsp;
  <strong>Track:</strong> {track} &nbsp;|&nbsp;
  <strong>Profile:</strong> {profile} &nbsp;|&nbsp;
  <strong>Benchmark:</strong> v{benchmark_version} &nbsp;|&nbsp;
  <strong>Date:</strong> {timestamp}
</div>

<h2>Summary</h2>
<div class="summary">
  <div class="metric agentic">
    <div class="value">{recall}</div>
    <div class="label">Target Hit Rate</div>
  </div>
  <div class="metric">
    <div class="value">{mixed_intent_accuracy}</div>
    <div class="label">Intent Accuracy</div>
  </div>
  <div class="metric">
    <div class="value">{capability_fp_rate}</div>
    <div class="label">Capability Noise</div>
  </div>
  {precision_metric}
</div>
{track_note}

<h2>Per-Track Breakdown</h2>
<table>
  <thead>
    <tr>
      <th>Track</th>
      <th>Cases</th>
      <th>Findings</th>
      <th class="tp">Targets Hit</th>
      <th class="fn">Targets Missed</th>
      <th class="fp">Additional</th>
      <th class="cap-fp">Cap Noise</th>
    </tr>
  </thead>
  <tbody>
    {track_rows}
  </tbody>
</table>

{profile_section}

<h2>Per-Case Results</h2>
<table>
  <thead>
    <tr>
      <th>Case ID</th>
      <th>Track</th>
      <th>Type</th>
      <th>Language</th>
      <th>Findings</th>
      <th class="tp">Targets Hit</th>
      <th class="fn">Missed</th>
      <th class="fp">Additional</th>
      <th class="cap-fp">Cap Noise</th>
      <th>Invocation</th>
      <th>Raw Output</th>
    </tr>
  </thead>
  <tbody>
    {case_rows}
  </tbody>
</table>

{deep_section}

<footer>
  Generated by SASTbench v{benchmark_version} &mdash;
  <em>Can your scanner find real vulnerabilities in agentic repos
  without flagging the code the agent is supposed to run?</em>
</footer>
</body>
</html>
"""


PR_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SASTbench PR Report - {scanner_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.5rem; }}
  .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
  .metric {{ background: #f5f5f5; border-radius: 8px; padding: 1rem; text-align: center; }}
  .metric .value {{ font-size: 2rem; font-weight: bold; }}
  .metric .label {{ font-size: 0.85rem; color: #666; margin-top: 0.25rem; }}
  .pr-primary {{ background: #e3f2fd; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1.5rem 0; }}
  th, td {{ padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #ddd; vertical-align: top; }}
  th {{ background: #f5f5f5; font-weight: 600; }}
  .tp {{ color: #2e7d32; }}
  .fn {{ color: #c62828; }}
  .cap-fp {{ color: #e65100; }}
  .fp {{ color: #f57f17; }}
  .detected {{ color: #2e7d32; font-weight: 600; }}
  .missed {{ color: #c62828; font-weight: 600; }}
  .mono {{ font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 0.85rem; word-break: break-word; }}
  .small {{ color: #666; font-size: 0.85rem; }}
  details {{ margin: 0.5rem 0 1rem 0; }}
  summary {{ cursor: pointer; font-weight: 600; padding: 0.3rem 0; }}
  .finding {{ border-left: 3px solid #ddd; padding: 0.5rem 0.75rem; margin: 0.4rem 0; font-size: 0.85rem; }}
  .finding.review {{ border-color: #1565c0; background: #e3f2fd; }}
  .finding.baseline {{ border-color: #9e9e9e; background: #f5f5f5; }}
  .finding .tag {{ display: inline-block; padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 0.75rem; font-weight: 600; color: #fff; margin-right: 0.5rem; }}
  .finding .tag.review {{ background: #1565c0; }}
  .finding .tag.baseline {{ background: #9e9e9e; }}
  .finding .meta {{ color: #555; font-size: 0.8rem; }}
  .changed-files {{ font-size: 0.85rem; margin: 0.5rem 0; }}
  .changed-files code {{ background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 2px; }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #999; font-size: 0.8rem; }}
</style>
</head>
<body>
<h1>SASTbench PR Report</h1>
<div class="meta">
  <strong>Scanner:</strong> {scanner_name} v{scanner_version} &nbsp;|&nbsp;
  <strong>Mode:</strong> PR Simulation &nbsp;|&nbsp;
  <strong>Track:</strong> {track} &nbsp;|&nbsp;
  <strong>Benchmark:</strong> v{benchmark_version} &nbsp;|&nbsp;
  <strong>Date:</strong> {timestamp}
</div>

<h2>PR Summary</h2>
<div class="summary">
  <div class="metric pr-primary">
    <div class="value">{introduced_target_hit_rate}</div>
    <div class="label">Introduced Target Hit Rate</div>
  </div>
  <div class="metric">
    <div class="value">{total_review_noise}</div>
    <div class="label">Review Noise</div>
  </div>
  <div class="metric">
    <div class="value">{total_capability_noise}</div>
    <div class="label">Capability Noise</div>
  </div>
  <div class="metric">
    <div class="value">{cases_evaluated}</div>
    <div class="label">Cases Evaluated</div>
  </div>
</div>
<p class="small"><strong>Note:</strong> PR mode compares base (clean) and head (vulnerable) trees.
"Review findings" are new-in-head findings. Introduced target hit rate measures whether
the scanner detects vulnerabilities introduced by the simulated PR.</p>

<h2>Per-Case PR Results</h2>
<table>
  <thead>
    <tr>
      <th>Case ID</th>
      <th>Type</th>
      <th>Lang</th>
      <th>Changed Files</th>
      <th>Base Findings</th>
      <th>Head Findings</th>
      <th>Review Findings</th>
      <th class="tp">Targets Detected</th>
      <th class="fp">Review Noise</th>
      <th class="cap-fp">Cap Noise</th>
      <th>Outcome</th>
    </tr>
  </thead>
  <tbody>
    {pr_case_rows}
  </tbody>
</table>

{deep_section}

<footer>
  Generated by SASTbench v{benchmark_version} &mdash;
  <em>Can your scanner catch vulnerabilities introduced in pull requests?</em>
</footer>
</body>
</html>
"""


def format_pct(value: float) -> str:
    return f"{value:.1%}"


def rebase_link(relative_path: str | None, results_dir: Path, output_dir: Path) -> str | None:
    """Rebase a stored artifact path from results-dir-relative to report-dir-relative."""
    if not relative_path:
        return None
    target = (results_dir / relative_path).resolve()
    return os.path.relpath(target, output_dir).replace("\\", "/")


def join_command(command: list[str] | None) -> str:
    """Render a command invocation compactly for HTML."""
    if not command:
        return "-"
    return " ".join(html.escape(part) for part in command)


def render_raw_links(artifacts: dict, results_dir: Path, output_dir: Path) -> str:
    """Render links to raw stdout/stderr artifacts."""
    links = []

    stdout_link = rebase_link(artifacts.get("rawStdoutPath"), results_dir, output_dir)
    stderr_link = rebase_link(artifacts.get("rawStderrPath"), results_dir, output_dir)
    if stdout_link:
        links.append(f"<a href=\"{html.escape(stdout_link)}\">stdout</a>")
    if stderr_link:
        links.append(f"<a href=\"{html.escape(stderr_link)}\">stderr</a>")

    skip_reason = artifacts.get("skipReason")
    if skip_reason:
        links.append(f"<span class=\"small\">skip:{html.escape(skip_reason)}</span>")

    return " | ".join(links) if links else "-"


def _classification_css(cls: str) -> str:
    """Return CSS class for a finding classification."""
    if cls == "true_positive":
        return "tp"
    if cls == "capability_false_positive":
        return "cap-fp"
    return "fp"


def _classification_label(cls: str) -> str:
    """Return a short label for a finding classification."""
    return {
        "true_positive": "TP",
        "false_positive": "FP",
        "capability_false_positive": "CAP FP",
    }.get(cls, cls.upper())


def render_finding_card(finding: dict) -> str:
    """Render one finding as an HTML card."""
    cls = finding.get("classification", "false_positive")
    css = _classification_css(cls)
    label = _classification_label(cls)
    region = finding.get("matchedRegionId") or "-"
    path = html.escape(finding.get("path", ""))
    start = finding.get("startLine", "?")
    end = finding.get("endLine", "?")
    kind = html.escape(finding.get("mappedKind", ""))
    rule = html.escape(finding.get("ruleId", ""))
    msg = html.escape(finding.get("message", ""))
    sev = html.escape(finding.get("severity", ""))

    return (
        f'<div class="finding {css}">'
        f'<span class="tag {css}">{label}</span>'
        f'<span class="mono">{path}:{start}-{end}</span>'
        f'<div class="meta">kind={kind} &nbsp; rule={rule} &nbsp; severity={sev} &nbsp; region={region}</div>'
        f'{"<div>" + msg + "</div>" if msg else ""}'
        f'</div>'
    )


def render_case_deep_section(case_result: dict) -> str:
    """Render a collapsible deep-detail section for one case."""
    findings = case_result.get("findings", [])
    case_id = html.escape(case_result["caseId"])
    tp = case_result["scoring"]["truePositives"]
    fn = case_result["scoring"]["falseNegatives"]
    fp = case_result["scoring"]["falsePositives"]
    cap_fp = case_result["scoring"]["capabilityFalsePositives"]

    if findings:
        cards = "\n".join(render_finding_card(f) for f in findings)
    else:
        cards = '<div class="finding"><em>No findings from scanner.</em></div>'

    return (
        f'<details>'
        f'<summary>{case_id} -- {len(findings)} findings '
        f'(<span class="tp">{tp} TP</span>, '
        f'<span class="fn">{fn} FN</span>, '
        f'<span class="fp">{fp} FP</span>, '
        f'<span class="cap-fp">{cap_fp} CapFP</span>)</summary>'
        f'{cards}'
        f'</details>'
    )


def _render_pr_finding_card(finding: dict, tag: str) -> str:
    """Render a PR finding card (review or baseline)."""
    css = "review" if tag == "REVIEW" else "baseline"
    path = html.escape(finding.get("path", ""))
    start = finding.get("startLine", "?")
    end = finding.get("endLine", "?")
    kind = html.escape(finding.get("mappedKind", ""))
    rule = html.escape(finding.get("ruleId", ""))
    msg = html.escape(finding.get("message", ""))

    return (
        f'<div class="finding {css}">'
        f'<span class="tag {css}">{tag}</span>'
        f'<span class="mono">{path}:{start}-{end}</span>'
        f'<div class="meta">kind={kind} &nbsp; rule={rule}</div>'
        f'{"<div>" + msg + "</div>" if msg else ""}'
        f'</div>'
    )


def _render_pr_case_deep(case_result: dict) -> str:
    """Render a collapsible PR deep-detail section for one case."""
    case_id = html.escape(case_result["caseId"])
    pr_ctx = case_result.get("prContext", {})
    pr_score = case_result.get("prScoring", {})

    changed = pr_ctx.get("changedFiles", [])
    baseline = pr_ctx.get("baselineFindings", [])
    head = pr_ctx.get("headFindings", [])
    review = pr_ctx.get("reviewFindings", [])

    detected = pr_score.get("introducedTargetsDetected", 0)
    total = pr_score.get("introducedTargetsTotal", 0)
    outcome_css = "detected" if detected == total and total > 0 else "missed"
    outcome_text = f"{detected}/{total} targets"

    parts = []
    parts.append(
        f'<details>'
        f'<summary>{case_id} &mdash; '
        f'<span class="{outcome_css}">{outcome_text}</span>, '
        f'{len(review)} review findings</summary>'
    )

    # Changed files
    if changed:
        parts.append('<div class="changed-files"><strong>Changed files:</strong><br>')
        for cf in changed[:20]:
            parts.append(f'<code>{html.escape(cf)}</code><br>')
        if len(changed) > 20:
            parts.append(f'<em>... and {len(changed) - 20} more</em>')
        parts.append('</div>')

    # Review findings
    parts.append(f'<h4>Review Findings ({len(review)} new-in-head)</h4>')
    if review:
        for rf in review:
            parts.append(_render_pr_finding_card(rf, "REVIEW"))
    else:
        parts.append('<div class="finding"><em>No new findings in head.</em></div>')

    # Baseline findings
    parts.append(f'<h4>Baseline Findings ({len(baseline)} in base)</h4>')
    if baseline:
        for bf in baseline[:10]:
            parts.append(_render_pr_finding_card(bf, "BASE"))
        if len(baseline) > 10:
            parts.append(f'<div class="finding"><em>... and {len(baseline) - 10} more</em></div>')
    else:
        parts.append('<div class="finding"><em>No findings in base tree.</em></div>')

    parts.append('</details>')
    return "\n".join(parts)


def generate_pr_report(results: dict, results_dir: Path, output_dir: Path, deep: bool = False) -> str:
    """Generate PR mode HTML report."""
    scanner = results["scanner"]
    pr_summary = results.get("prSummary", {})

    pr_case_rows = []
    for cr in results["caseResults"]:
        pr_ctx = cr.get("prContext", {})
        pr_score = cr.get("prScoring", {})

        changed_count = len(pr_ctx.get("changedFiles", []))
        base_count = len(pr_ctx.get("baselineFindings", []))
        head_count = len(pr_ctx.get("headFindings", []))
        review_count = len(pr_ctx.get("reviewFindings", []))

        detected = pr_score.get("introducedTargetsDetected", 0)
        total = pr_score.get("introducedTargetsTotal", 0)
        outcome_css = "detected" if detected == total and total > 0 else "missed"
        outcome_text = "DETECTED" if detected == total and total > 0 else "MISSED"

        pr_case_rows.append(
            f"<tr>"
            f"<td>{html.escape(cr['caseId'])}</td>"
            f"<td>{html.escape(cr['caseType'])}</td>"
            f"<td>{html.escape(cr['language'])}</td>"
            f"<td>{changed_count}</td>"
            f"<td>{base_count}</td>"
            f"<td>{head_count}</td>"
            f"<td>{review_count}</td>"
            f"<td class='tp'>{detected}/{total}</td>"
            f"<td class='fp'>{pr_score.get('reviewNoise', 0)}</td>"
            f"<td class='cap-fp'>{pr_score.get('capabilityNoise', 0)}</td>"
            f"<td class='{outcome_css}'>{outcome_text}</td>"
            f"</tr>"
        )

    deep_html = ""
    if deep:
        deep_parts = ['<h2>PR Finding-Level Audit Trail</h2>',
                       '<p>Expand a case to see changed files, review findings, and baseline findings.</p>']
        for cr in results["caseResults"]:
            deep_parts.append(_render_pr_case_deep(cr))
        deep_html = "\n".join(deep_parts)

    return PR_HTML_TEMPLATE.format(
        scanner_name=html.escape(scanner["name"]),
        scanner_version=html.escape(scanner["version"]),
        track=html.escape(results["track"]),
        benchmark_version=html.escape(results["benchmarkVersion"]),
        timestamp=html.escape(results["timestamp"][:10]),
        introduced_target_hit_rate=format_pct(pr_summary.get("introducedTargetHitRate", 0)),
        total_review_noise=pr_summary.get("totalReviewNoise", 0),
        total_capability_noise=pr_summary.get("totalCapabilityNoise", 0),
        cases_evaluated=pr_summary.get("casesEvaluated", 0),
        pr_case_rows="\n".join(pr_case_rows),
        deep_section=deep_html,
    )


def generate_report(results: dict, results_dir: Path, output_dir: Path, deep: bool = False) -> str:
    """Generate HTML report from results JSON. Routes to PR report if mode=pr."""
    if results.get("mode") == "pr":
        return generate_pr_report(results, results_dir, output_dir, deep)

    summary = results["summary"]
    scanner = results["scanner"]

    track_totals: dict[str, dict[str, int]] = {}
    for cr in results["caseResults"]:
        track_key = cr["caseTrack"]
        bucket = track_totals.setdefault(track_key, {
            "cases": 0,
            "findings": 0,
            "tp": 0,
            "fn": 0,
            "fp": 0,
            "cap_fp": 0,
        })
        bucket["cases"] += 1
        bucket["findings"] += len(cr["findings"])
        bucket["tp"] += cr["scoring"]["truePositives"]
        bucket["fn"] += cr["scoring"]["falseNegatives"]
        bucket["fp"] += cr["scoring"]["falsePositives"]
        bucket["cap_fp"] += cr["scoring"]["capabilityFalsePositives"]

    track_rows = []
    for track_name in sorted(track_totals):
        totals = track_totals[track_name]
        track_rows.append(
            f"<tr>"
            f"<td>{html.escape(track_name)}</td>"
            f"<td>{totals['cases']}</td>"
            f"<td>{totals['findings']}</td>"
            f"<td class='tp'>{totals['tp']}</td>"
            f"<td class='fn'>{totals['fn']}</td>"
            f"<td class='fp'>{totals['fp']}</td>"
            f"<td class='cap-fp'>{totals['cap_fp']}</td>"
            f"</tr>"
        )

    profile_totals: dict[str, dict[str, int]] = {}
    for cr in results["caseResults"]:
        bucket_key = "agentic" if cr.get("agentic", True) else "generic"
        bucket = profile_totals.setdefault(bucket_key, {
            "cases": 0,
            "findings": 0,
            "tp": 0,
            "fn": 0,
            "fp": 0,
            "cap_fp": 0,
        })
        bucket["cases"] += 1
        bucket["findings"] += len(cr["findings"])
        bucket["tp"] += cr["scoring"]["truePositives"]
        bucket["fn"] += cr["scoring"]["falseNegatives"]
        bucket["fp"] += cr["scoring"]["falsePositives"]
        bucket["cap_fp"] += cr["scoring"]["capabilityFalsePositives"]

    if len(profile_totals) > 1:
        profile_rows = []
        for profile_name in ("agentic", "generic"):
            totals = profile_totals.get(profile_name)
            if not totals:
                continue
            profile_rows.append(
                f"<tr>"
                f"<td>{profile_name}</td>"
                f"<td>{totals['cases']}</td>"
                f"<td>{totals['findings']}</td>"
                f"<td class='tp'>{totals['tp']}</td>"
                f"<td class='fn'>{totals['fn']}</td>"
                f"<td class='fp'>{totals['fp']}</td>"
                f"<td class='cap-fp'>{totals['cap_fp']}</td>"
                f"</tr>"
            )
        profile_section = (
            "<h2>Per-Profile Breakdown</h2>\n"
            "<table>\n"
            "  <thead><tr>"
            "<th>Profile</th><th>Cases</th><th>Findings</th>"
            "<th class='tp'>Targets Hit</th><th class='fn'>Targets Missed</th>"
            "<th class='fp'>Additional</th><th class='cap-fp'>Cap Noise</th>"
            "</tr></thead>\n"
            f"  <tbody>\n{chr(10).join(profile_rows)}\n  </tbody>\n"
            "</table>"
        )
    else:
        profile_section = ""

    case_rows = []
    for cr in results["caseResults"]:
        s = cr["scoring"]
        artifacts = cr.get("artifacts", {})
        case_rows.append(
            f"<tr>"
            f"<td>{html.escape(cr['caseId'])}</td>"
            f"<td>{html.escape(cr['caseTrack'])}</td>"
            f"<td>{html.escape(cr['caseType'])}</td>"
            f"<td>{html.escape(cr['language'])}</td>"
            f"<td>{len(cr['findings'])}</td>"
            f"<td class='tp'>{s['truePositives']}</td>"
            f"<td class='fn'>{s['falseNegatives']}</td>"
            f"<td class='fp'>{s['falsePositives']}</td>"
            f"<td class='cap-fp'>{s['capabilityFalsePositives']}</td>"
            f"<td class='mono'>{join_command(artifacts.get('commandInvocation'))}</td>"
            f"<td>{render_raw_links(artifacts, results_dir, output_dir)}</td>"
            f"</tr>"
        )

    deep_html = ""
    if deep:
        deep_parts = []
        deep_parts.append("<h2>Finding-Level Audit Trail</h2>")
        deep_parts.append("<p>Expand a case to see every finding with its classification.</p>")
        for cr in results["caseResults"]:
            deep_parts.append(render_case_deep_section(cr))
        deep_html = "\n".join(deep_parts)

    # Precision only in deep/verbose mode
    if deep:
        precision_metric = (
            f'<div class="metric">'
            f'<div class="value">{format_pct(summary["precision"])}</div>'
            f'<div class="label">Precision</div>'
            f'</div>'
        )
    else:
        precision_metric = ""

    # Track-aware context note
    track_key = results["track"]
    if track_key == "full":
        track_note = (
            '<p class="small"><strong>Note:</strong> Full Track includes real-world disclosed cases. '
            '"Additional findings" on these cases may be legitimate issues in the target repo, '
            'not necessarily false positives. Only the disclosed target vulnerability is scored.</p>'
        )
    else:
        track_note = (
            '<p class="small"><strong>Note:</strong> Core Track cases are self-contained synthetic benchmarks '
            'with strictly defined vulnerable and safe regions.</p>'
        )

    html_output = HTML_TEMPLATE.format(
        scanner_name=html.escape(scanner["name"]),
        scanner_version=html.escape(scanner["version"]),
        track=html.escape(results["track"]),
        profile=html.escape(results.get("profile", "all")),
        benchmark_version=html.escape(results["benchmarkVersion"]),
        timestamp=html.escape(results["timestamp"][:10]),
        recall=format_pct(summary["recall"]),
        capability_fp_rate=format_pct(summary["capabilityFpRate"]),
        precision_metric=precision_metric,
        mixed_intent_accuracy=format_pct(summary["mixedIntentAccuracy"]),
        track_rows="\n".join(track_rows),
        case_rows="\n".join(case_rows),
        profile_section=profile_section,
        deep_section=deep_html,
        track_note=track_note,
    )

    return html_output


def main() -> int:
    parser = argparse.ArgumentParser(description="SASTbench HTML report generator")
    parser.add_argument("results", type=Path, help="Results JSON file")
    parser.add_argument("--output", "-o", type=Path, help="Output HTML file")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Include per-finding audit trail in the report")
    args = parser.parse_args()

    if not args.results.exists():
        print(f"Results file not found: {args.results}")
        return 1

    with open(args.results, encoding="utf-8") as f:
        results = json.load(f)

    output = args.output or args.results.with_suffix(".html")
    html_output = generate_report(results, args.results.parent.resolve(), output.parent.resolve(), deep=args.verbose)

    with open(output, "w", encoding="utf-8") as f:
        f.write(html_output)

    print(f"Report written to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
